### ISSUE TITLE
It not work with nextjs v6.1.2

### ISSUE THREAD

**Issue by pvhieuit** [blainegarrett/node-next-gae-demo#1]
Hi @blainegarrett 
Thank you for the sample it works very well.
But when I changed the latest version of nextjs(6.1.2) it is faulty.

package.json
```javascript
"dependencies": {
    "express": "^4.16.3",
    "isomorphic-unfetch": "^2.1.1",
    "next": "^6.1.2",
    "prop-types": "^15.6.2",
    "react": "^16.5.0",
    "react-dom": "^16.5.0"
  }
```
URL sample with nextjs 6.1.2: https://node-next-gae-demo-dot-nextjs-app-215410.appspot.com/
Error Log: 
![image](https://user-images.githubusercontent.com/18276928/45256854-6a1d4600-b3c6-11e8-8d94-c6e3cc2866bb.png)

Can you hepl me?
Thanks again!

**Comment by blainegarrett** [comment]
@pvhieuit I'll upgrade things this week. I did manage to get latest Next and other things running again this week on a separate project. It isn't too painful.

**Comment by pvhieuit** [comment]
@blainegarrett I hope you have a fix, it took me a whole week to fix it, but it was too hard for me.

**Comment by blainegarrett** [comment]
@pvhieuit if you are in a hurry, you should be able to clone the [express example](https://github.com/zeit/next.js/tree/master/examples/custom-server-express) from the nextjs examples folder. The only real GAE specific things from this project are the app.yaml and some of the config. This demo doesn't use any datastore, etc.

**Comment by pvhieuit** [comment]
@blainegarrett I'm not in a hurry. I will wait for information from you.
Do you think the reason is that I deployed with Windows?

**Comment by blainegarrett** [comment]
@pvhieuit Could you try installing the latest master? If it works for you, I'll cut a new major release.
Here is the PR for the changes I made https://github.com/blainegarrett/node-next-gae-demo/pull/2

That said, I didn't have to do much aside from pinning the next and react versions to match what you posted from your package.json to get this working.

Things to check on your end:
 - Did you run `npm run build` before you deployed? 
- Do you get an error when running the example locally? `npm run dev` and then navigate to localhost:3000
- Do you get an error when running the production build locally? `npm run build` and then `npm run start` and then navigate to localhost:8080

**Comment by pvhieuit** [comment]
Hi @blainegarrett 
Thank you for your support, It still does not work on GAE.

Error
> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

I think the problem is due to nextjs on Windows (I'm using Windows 10) [Issues Nextjs building on Windows.](https://github.com/zeit/next.js/issues/5132#issuecomment-420549772)

**Comment by blainegarrett** [comment]
Interesting. This seems to be an issue with Next resolving paths. I'm on Mac so I won't be able to recreate.
