### ISSUE TITLE
GAE 10000 files limit exceeded ERROR during deploy

### ISSUE THREAD

**Issue by maxdyy** [blainegarrett/node-next-gae-demo#3]
Hey, I'm trying to deploy this demo to my GAE instance, but it gave me the following error:

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This deployment has too many files. New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to 10000
      files for this app.
    field: version.deployment.files[...]
```

Do I have to skip the node_modules folder in the deploy? 🤔

**Comment by blainegarrett** [comment]
You likely need to upgrade gcloud. Skip files directive  in app yaml has
been replaced with .cloudignore file for most of gcloud.

**Comment by maxdyy** [comment]
Nice, updated my gcloud sdk and it worked like magic!
Thanks

**Comment by blainegarrett** [comment]
@maxdyy  Glad that worked. Also note, I just cut a new release which upgrades to the latest version of next as well as sets things up for the nodejs 10 runtime. 

Check out this commit: https://github.com/blainegarrett/node-next-gae-demo/commit/810671685ebde898cdb3f2c506fb99a45f8c471a

**Comment by Madhusudhan77** [comment]
Hi ,

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This deployment has too many files.
 New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to
 10000
      files for this app.
    field: version.deployment.files[...]

Even myself facing the same issue while deploying my python app using flask framework.I tried all alternatives but none of them working.

Any inputs might be handy here?

**Comment by blainegarrett** [comment]
@Madhusudhan77 Are you deploying from the project root directory? The `.cloudignore` doesn't seem like it is being obeyed. 
The likely culprit for this project is the node_modules directory, which can be skipped for deploy. 

I'm a bit behind on my gcloud updates but here is my version I deployed with a few days ago:
```
$gcloud --version
Google Cloud SDK 305.0.0
app-engine-java 1.9.81
app-engine-python 1.9.91
beta 2020.08.07
bq 2.0.58
cloud-datastore-emulator 2.1.0
core 2020.08.07
gsutil 4.52
```

**Comment by madhavthatavarthi** [comment]
@blainegarrett I am trying to deploy nodejs code to GCP App engine using gcloud but getting error this deployment has too many files. I ignored node_modules files in .gcloudignore. I dont know why it is throwing error. PFA image.

My gcloud version is:
$gcloud --version
Google Cloud SDK 326.0.0
beta 2021.01.29
bq 2.0.64
cloud-datastore-emulator 2.1.0
core 2021.01.29
gsutil 4.58


![image](https://user-images.githubusercontent.com/13845394/106866705-c9e0be00-66f2-11eb-947e-847e23974ad7.png)

**Comment by Hyperledger04** [comment]
You can check out how many files are there in your root directory by using dir /a-d /w /s "C:\Users\acer\Desktop\project directory" | find /v /c "::" in your CLI and then you can use tree command to check the structure of files. You may install tree on your machine first from https://sourceforge.net/projects/gnuwin32/files/tree/1.5.2.2/tree-1.5.2.2-src-setup.exe/download this link and then run tree command. Accordingly add the files which are unnecessary in your .gcloudignore file in your root directory. In my case I skipped venv components while deploying the python app and it worked for me.
